### ISSUE TITLE
Reviews datePublished: ISO 8601 format required

### ISSUE THREAD

**Issue by lat9** [torvista/Structured-Data-for-Zen-Cart#1]
Great plugin!  I especially like that you've put the primary processing into a jscript file, enabling quick use in any template!

Going through the reviews section, though, the current processing for a review's dataPublished:
>     "datePublished" : "<?php echo zen_date_short($reviewArray[$i]['dateAdded']); ?>",
will use the date-formatting defined for the store.  Google's [requirements ](https://developers.google.com/search/docs/data-types/reviews)indicate that the date should be in ISO 8601 format (essentially `yyyy-mm-dd`), so I've changed my version to read:
>     "datePublished" : "<?php echo substr($reviewArray[$i]['dateAdded'], 0, 10); ?>",

**Comment by torvista** [comment]
Well spotted.
"Interestingly" the GSD Tool accepts/does not complain about dates with slashes in.
![date](https://cloud.githubusercontent.com/assets/4391026/24818060/488655b6-1bdf-11e7-8432-dc60a0bac015.jpg)

**Comment by lat9** [comment]
Google's tools don't always align with their requirements!
