### ISSUE TITLE
Warning in logfiles

### ISSUE THREAD

**Issue by BramF33** [torvista/Structured-Data-for-Zen-Cart#3]
I am getting warnings in my logfiles:

PHP Warning:  Division by zero in /var/www/xxxx/includes/templates/xxx/jscript/jscript_plugin_structured_data.php on line 280

Can this be fixed? I am on zen-cart 1.55e

**Comment by torvista** [comment]
Is this a new install of the plugin?
Do you have a link to the page that causes the error?
Is this your line 208?
`      "@id": "<?php echo $value[$i]['link']; ?>",`
